# Generated by Django 4.2.8 on 2023-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exceprt',
            field=models.TextField(blank=True),
        ),
    ]
